version: '3.8'
services:
  redis:
    image: redis:7.2
    container_name: redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  redis_data:
